language: cpp

compiler: 
  - gcc
  - clang

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  
script:
  - mkdir build
  - cd build
  - cmake ../ -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $CXX)
  - make